alias open="xdg-open"
alias cls='clear'
alias aptg='sudo apt-get'
alias apt-update='sudo apt-get update'
alias sapt='sudo apt'
alias apti='sudo apt --assume-yes install'
alias aptr='sudo apt --assume-yes remove'
alias npmig='sudo npm install -g'
alias create-launcher='gnome-desktop-item-edit --create-new ~/.local/share/applications'
alias code='code-insiders'
alias xclipb='xclip -sel clip'
alias ports='netstat -ntlp'
alias l='exa -lgha --git'
alias la='exa -lghaa --git'
alias ll='exa -lgh --git'
alias debi='sudo dpkg -i'
alias pmi='sudo pacman -S --noconfirm --needed'
alias yai='yay -S --noconfirm --needed'
alias dps='docker ps'
alias dimg='docker images'
alias drm='docker rm'
alias drmi='docker rmi'
alias docker-rm-none="docker images | grep none | awk '{print \$3}' | xargs docker rmi"
alias ghci='stack ghci'
alias gpl='git pull origin'
alias rusti="rustup run nightly-2016-08-01 ~/.cargo/bin/rusti"
alias pipi="pip install --upgrade"
alias pipu="pip install --user --upgrade"
alias pip-upgrade="sudo pip install --upgrade pip"
alias pe="path-extractor"
alias -g PE='| pe | fzf | read filename; [ ! -z $filename ] && nvim $filename'
alias -g PEC='| pe | fzf | read filename; [ ! -z $filename ] && echo -n $filename | xclip -sel c'
