#!/bin/sh

# set environment variables
export PATH="$HOME/private_dotfiles/bin:$HOME/dotfiles/bin:$PATH"
export QT_QPA_PLATFORMTHEME=qt5ct
export ZK_NOTEBOOK_DIR=~/pwiki
export SDL_GAMECONTROLLERCONFIG='03000000c82d00000b31000014010000,8BitDo Ultimate 2 Wireless Controller,a:b0,b:b1,x:b2,y:b3,back:b6,guide:b8,start:b7,leftstick:b9,rightstick:b10,leftshoulder:b4,rightshoulder:b5,dpup:h0.1,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,leftx:a0,lefty:a1,rightx:a3,righty:a4,lefttrigger:a2,righttrigger:a5,platform:Linux,'
